### ISSUE TITLE
Launch this application as admin 

### ISSUE THREAD

**Issue by xMeftu** [CodeSpent/twitch-clip-manager#7]
Hello, i run as admin clip-manager.exe and;
I go to configure, after enter i see fast message Please lunch this application as admin to configure - and window close in 1-2 seconds

**Comment by CodeSpent** [comment]
Hey, unfortunately I did catch this but was much too tired to fix in the moment. I have #5 opened for this which includes a workaround by creating the configuration manually.

I am rethinking this approach all together, though, I don't believe I want to ask for admin rights at all, however, I need to have a way to persist the Client ID & Secret for the user, so will need to think on this.

Try out the workaround & see if it works for you.

**Comment by CodeSpent** [comment]
This is fixed with #8 and will be resolved for v0.0.3 release if you want to give it another shot!
